//
//  MoviesModels.swift
//  TheMovieDB
//
//  Created by Usuario on 28/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesScene
{
  // MARK: Use cases

  enum GetMovies
  {
    struct Request {
        let page: Int
    }
    struct Response {
        let response: MoviesResponse
    }
    struct ViewModel {
        let response: MoviesResponse
    }
  }
    
  enum SelectMovie
  {
    struct Request {
      let movie: Movie
    }
    struct Response {}
    struct ViewModel {}
  }
}
