//
//  MoviesPresenter.swift
//  TheMovieDB
//
//  Created by Usuario on 28/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic
{
  func presentMovies(response: MoviesScene.GetMovies.Response)
  func presentSelectedMovie(response: MoviesScene.SelectMovie.Response)
}

class MoviesPresenter: MoviesPresentationLogic
{
  weak var viewController: MoviesDisplayLogic?
  
  // MARK: Do something
    
  func presentMovies(response: MoviesScene.GetMovies.Response) {
    let viewModel = MoviesScene.GetMovies.ViewModel(response: response.response)
    viewController?.displayMovies(viewModel: viewModel)
  }
    
  func presentSelectedMovie(response: MoviesScene.SelectMovie.Response) {
    let viewModel = MoviesScene.SelectMovie.ViewModel()
    viewController?.displaySelectedMovie(viewModel: viewModel)
  }
}
