# rule identifiers to include from running
whitelist_rules:
- trailing_newline
- opening_brace
#    - variable_name_min_length
- trailing_semicolon
#    - conditional_binding_cascade
#    - variable_name_max_length
- operator_whitespace
- return_arrow_whitespace
- closing_brace
- leading_whitespace
- redundant_string_enum_value
- trailing_comma
- vertical_parameter_alignment
- vertical_whitespace
- redundant_discardable_let
#    - notification_center_detachment
#    - empty_enum_arguments
#    -empty_count
#    -colon
#    -comma
#    -force_cast
#    -type_name
#    -force_try
#    -function_body_length
#    -nesting
#    -variable_name
#    -control_statement
#    -legacy_constant
#    -line_length
#    -trailing_whitespace
#    -statement_position
#    -type_body_length
#    -todo
#    -legacy_constructor
#    -valid_docs
#    -missing_docs
#    -file_length
#    -class_delegate_protocol
#    -closure_parameter_position
#    -compiler_protocol_init
#    -cyclomatic_complexity
#    -dynamic_inline
#    -empty_parameters
#    -empty_parentheses_with_trailing_closure
#    -function_parameter_count
#    -generic_type_name
#    -implicit_getter
#    -large_tuple
#    -legacy_cggeometry_functions
#    -legacy_nsgeometry_functions
#    -mark
#    -private_unit_test
#    -redundant_optional_initialization
#    -redundant_void_return
#    -shorthand_operator
#    -syntactic_sugar
#    -unused_closure_parameter
#    -unused_enumerated
#    -unused_optional_binding
#    -valid_ibinspectable
#    -void_return
#    -weak_delegate
#    -for_where
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods