//
//  TabBarInteractor.swift
//  TheMovieDB
//
//  Created by Usuario on 28/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabBarBusinessLogic
{
  func getRootViewControllers(request: TabBarScene.RootViewControllers.Request)
}

protocol TabBarDataStore {}

class TabBarInteractor: TabBarBusinessLogic, TabBarDataStore
{
  var presenter: TabBarPresentationLogic?

  func getRootViewControllers(request: TabBarScene.RootViewControllers.Request) {
    let response = TabBarScene.RootViewControllers.Response(controllers: TabBarRootController.all)
    presenter?.presentRootViewControllers(response: response)
  }
}
