//
//  TabBarPresenter.swift
//  TheMovieDB
//
//  Created by Usuario on 28/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabBarPresentationLogic
{
  func presentRootViewControllers(response: TabBarScene.RootViewControllers.Response)
}

class TabBarPresenter: TabBarPresentationLogic
{
  weak var viewController: TabBarDisplayLogic?
  
  func presentRootViewControllers(response: TabBarScene.RootViewControllers.Response)
  {
    let viewModel = TabBarScene.RootViewControllers.ViewModel(controllers: response.controllers)
    viewController?.displayRootViewControllers(viewModel: viewModel)
  }
}
