//
//  DetailPresenter.swift
//  TheMovieDB
//
//  Created by Usuario on 29/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func presentStorageResult(response: DetailScene.AddMovie.Response)
    func presentDeleteMovie(response: DetailScene.DeleteMovie.Response)
    func presentIsFavorite(response: DetailScene.IsFavorite.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
    
  func presentStorageResult(response: DetailScene.AddMovie.Response) {
    let viewModel = DetailScene.AddMovie.ViewModel(result: response.result)
    viewController?.displayStorageResult(viewModel: viewModel)
  }

  func presentIsFavorite(response: DetailScene.IsFavorite.Response) {
    let viewModel = DetailScene.IsFavorite.ViewModel(result: response.result)
    viewController?.displayIsFavorite(viewModel: viewModel)
  }
    
  func presentDeleteMovie(response: DetailScene.DeleteMovie.Response) {
    let viewModel = DetailScene.DeleteMovie.ViewModel(result: response.result)
    viewController?.displayDeleteMovie(viewModel: viewModel)
  }
}
