//
//  DetailRouter.swift
//  TheMovieDB
//
//  Created by Usuario on 29/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic
{
}

protocol DetailDataPassing
{
  var dataStore: DetailDataStore? { get set }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing
{
  weak var viewController: DetailViewController?
  var dataStore: DetailDataStore?
  
  // MARK: Routing
}
