# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RicardoMartinsFeatureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RicardoMartinsFeatureDemo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 4.9.0'
  pod 'SDWebImage', '~> 5'
  pod 'lottie-ios'

end
