//
//  FavoritesRouter.swift
//  TheMovieDB
//
//  Created by Usuario on 28/01/20.
//  Copyright (c) 2020 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoritesRoutingLogic
{
  func navigateToDetailScene()
}

protocol FavoritesDataPassing
{
  var dataStore: FavoritesDataStore? { get }
}

class FavoritesRouter: NSObject, FavoritesRoutingLogic, FavoritesDataPassing
{
  weak var viewController: FavoritesViewController?
  var dataStore: FavoritesDataStore?
  
  // MARK: Routing
    
  func navigateToDetailScene() {
    guard let detailViewController = UIStoryboard(name: "Detail", bundle: nil)
        .instantiateViewController(withIdentifier: "DetailViewController") as? DetailViewController
       else { return }
       
    detailViewController.router?.dataStore?.movie = dataStore?.movie
    viewController?.navigationController?
        .pushViewController(detailViewController, animated: true)
  }
}
